scalar Email

type User {
  id: ID!
  email: Email!
  name: String!
}

type Query {
  user: User!
  users: [User!]!
}

type Mutation {
  createUser(input: CreateUserInput!): User!
  updateUser(id: ID!, input: UpdateUserInput!): User!
  deleteUser(id: ID!): User!
}

input CreateUserInput {
  email: Email!
  name: String!
}

input UpdateUserInput {
  email: Email
  name: String
}
